repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
     - id: mixed-line-ending
       args: [--fix=lf]
     - id: trailing-whitespace
     - id: end-of-file-fixer
