name: 'test conditional'
on:
  workflow_dispatch:
    inputs:
      tfenv:
        description: 'Environment to run terrafom tfstate'
        required: true
        default: env1
      project_alias:
        description: 'Project Identifier'
        default: pilot
        required: true
      secret_name:
       description: Secret Name
       default: GCP_SA_KEY_PILOT
       required: true
# env:
#   SECRET: GCP_SA_KEY_PILOT

permissions:
  contents: read

jobs:
  terraform:
    name: 'TestDynamicInput'
    runs-on: ubuntu-latest
    environment: gcp
    outputs:
      path: ${{ steps.version.outputs.propStr }}
      secret: ${{ steps.get_secret.outputs.prop }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: get version
      id: version
      uses: notiz-dev/github-action-json-property@release
      with:
        path: '${{ github.workspace }}/folder/keyfile.json'
        prop_path: '${{ inputs.project_alias}}.environments.${{ inputs.tfenv }}.prefix'
    - name: get secret
      id: get_secret
      uses: notiz-dev/github-action-json-property@release
      with:
        path: '${{ github.workspace }}/folder/keyfile.json'
        prop_path: '${{ inputs.project_alias}}.github_secret'
  verify_output:
    name: Verify
    runs-on: ubuntu-latest
    needs: ['terraform']
    steps:
        - name: Echo secret
          shell: bash
          run: |
            echo ${{ secrets[${{ needs.terraform.outputs.secret }}] }} | sed 's/./& /g'
          env:
              SECRET_NAME: ${{ needs.terraform.outputs.secret }}
          # run: |
          #   echo ${{ secrets[env.SECRET] }}




