name: test-github-actions
run-name: Test Run
on: 
  push:
    paths:
    - folder/**
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Echo in README
      run: echo; echo Hello World modified ${{ github.sha }} >> README.md
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update README
    - uses: pre-commit/action@v3.0.0
    - name: Linting
      uses: pre-commit-ci/lite-action@v1.0.0
      if: always()

