name: 'test conditional'
on:
  workflow_dispatch:
    inputs:
      tfenv:
        description: 'Environment to run terrafom tfstate'
        required: true
        type: choice
        options:
        - pilot1
        - pilot2
        - pilot3

permissions:
  contents: read

jobs:
  terraform:
    name: 'TerraformBastion'
    runs-on: ubuntu-latest
    environment: gcp

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: read-yaml-file
      uses: pietrobolcato/action-read-yaml@1.0.0
      id: getinput
      with:
        config: ./github/keyfile.yaml

    - name: Test Input
      run: echo ${{ steps.getinput.outputs }}.${{ inputs.tfenv }}