name: Boilerplate workflow
run-name: Generate boilerplate argocd-ska config

on:
  push:


jobs:
  Generate-Boilerplate:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Test secret
      run: echo ${{ secrets.DELOITTEXSP_AUTOMATION_GITHUB_TOKEN }}

    - name: Install Boilerplate
      run: |
        set -xeo pipefail
        sudo curl -Ls https://raw.githubusercontent.com/gruntwork-io/gruntwork-installer/"$GRUNTWORK_INSTALLER_VERSION"/bootstrap-gruntwork-installer.sh | bash /dev/stdin --version "$GRUNTWORK_INSTALLER_VERSION"
        gruntwork-install --binary-name 'terragrunt' --repo 'https://github.com/gruntwork-io/terragrunt' --tag "$TERRAGRUNT_VERSION" --no-sudo true
        gruntwork-install --binary-name 'boilerplate' --repo 'https://github.com/gruntwork-io/boilerplate' --tag "$BOILERPLATE_VERSION" --no-sudo true
      env:
        GRUNTWORK_INSTALLER_VERSION: v0.0.38
        TERRAGRUNT_VERSION: v0.40.2
        BOILERPLATE_VERSION: v0.5.3
        GITHUB_OAUTH_TOKEN: ${{ secrets.DELOITTEXSP_AUTOMATION_GITHUB_TOKEN }}

    - name: Verify Installation
      run: |
        set -e
        boilerplate -v
        terragrunt -v
        terraform -v

    - name: Generate Boilerplate Template
      shell: bash
      run: |
        set -xeo pipefail
        environments=$(git diff -r --name-only origin/main...HEAD | grep -E ^infrastructure-template/environments/ | xargs dirname | sort -u)
        for env in $environments; do if [ $(ls $env) ]; then boilerplate --template-url ./infrastructure-template/blueprints --output-folder .  --non-interactive --var-file $env/* ; fi; done

    - name: Push Boilerplate Output
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Generated boilerplate output

    - name: Run Linting Checks
      run: |
        pip install pre-commit
        pre-commit run --from-ref origin/main --to-ref HEAD --verbose
      continue-on-error: true

    - name: Push Lint Fix
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Fixed lint for boilerplate output
