name: 'test conditional'
on:
  workflow_dispatch:
    inputs:
      tfmode:
        description: 'Action foe terraform'
        required: true
      tfenv:
        description: 'Environment to run terrafom tfstate'
        required: true

permissions:
  contents: read

jobs:
  terraform:
    name: 'TestDynamicInput'
    runs-on: ubuntu-latest
    if: ${{ inputs.tfmode }} != "destroy"
    environment: gcp

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Output value
      run: echo "hello tfmode:${{ inputs.tfmode }} is not equal to destroy"
  destroy_job:
    name: 'Terraform Destroy Job'
    runs-on: ubuntu-latest
    if: ${{ inputs.tfmode }} == 'destroy'
    steps:
      - name: Output value
        run: echo "hello tfmode:${{ inputs.tfmode }} equals destroy"
   
