name: test-github-actions
run-name: Test Run
on:
  push:
    paths:
    - folder/**
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: checkout gruntwork
      uses: actions/checkout@v3
      with:
        repository: gruntwork-io/gruntwork-installer
        token: ${{ secrets.OAUTH_GITHUB_KEY }}

    - name: install boilerplate
      run: |
        sudo curl -Ls https://raw.githubusercontent.com/gruntwork-io/gruntwork-installer/v0.0.38/bootstrap-gruntwork-installer.sh | bash /dev/stdin --version v0.0.38
        gruntwork-install --binary-name 'terragrunt' --repo 'https://github.com/gruntwork-io/terragrunt' --tag "$TERRAGRUNT_VERSION" --no-sudo true
        gruntwork-install --binary-name 'boilerplate' --repo 'https://github.com/gruntwork-io/boilerplate' --tag "$BOILERPLATE_VERSION" --no-sudo true
      env:
        GRUNTWORK_INSTALLER_VERSION: v0.0.38
        TERRAGRUNT_VERSION: v0.40.2
        BOILERPLATE_VERSION: v0.5.3
        GITHUB_OAUTH_TOKEN: ${{ secrets.OAUTH_GITHUB_KEY }}

    - name: verify installation
      run: |
        terragrunt -v
        boilerplate -v
    # - name: Echo in README
    #   run: echo; echo Hello World modified ${{ github.sha }} >> README.md
    # - uses: stefanzweifel/git-auto-commit-action@v4
    #   with:
    #     commit_message: Update README
    # - uses: pre-commit/action@v3.0.0
    #   continue-on-error: true
    # - uses: stefanzweifel/git-auto-commit-action@v4
    # - name: Linting
    #   uses: pre-commit-ci/lite-action@v1.0.0
    #   if: always()
