name: 'test conditional'
on:
  workflow_dispatch:
    inputs:
      tfmode:
        description: 'Action for terraform'
        required: true
        default: plan
      tfenv:
        description: 'Environment to run terrafom tfstate'
        required: true
        default: pilot

permissions:
  contents: read

jobs:
  terraform:
    name: 'TestDynamicInput'
    runs-on: ubuntu-latest
    if: (github.event.inputs.tfmode == 'plan' || github.event.inputs.tfmode == 'apply')
    environment: gcp

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Output value
      run: echo "hello tfmode:${{ inputs.tfmode }} is not equal to destroy"
  destroy_job:
    name: 'Terraform Destroy Job'
    runs-on: ubuntu-latest
    if: (github.event.inputs.tfmode == 'destroy' )
    steps:
      - name: Output value
        run: echo "hello tfmode:${{ inputs.tfmode }} equals destroy"
   
