name: Boilerplate workflow
run-name: Generate boilerplate argocd-ska config

on:
  push:
    paths:
      - folder/**
    branches-ignore:
      - 'main'
      - 'master'

jobs:
  Generate-Boilerplate:
    if: github.event.pull_request.merged == false
    runs-on: ubuntu-latest
    steps:
    - name: 'Step 1 - Checkout'
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Run Linting Checks
      run: |
        pip install pre-commit
        pre-commit run --from-ref origin/main --to-ref HEAD --verbose
      continue-on-error: true

    - name: Push Lint Fix
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Fixed lint for boilerplate output
