name: 'pre-commit scan'
run-name: Generate ArgoCD SKA Config
on:
  push:

jobs:
  job1_run_pre_commit:
    name: 'Job 1 - Run pre-commit checks'
    runs-on: ubuntu-latest
    steps:
    - name: 'Step 1 - Checkout'
      uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: 3.8
    # - name: 'Step 5 - Generate boilerplate output'
    #   run: |
    #     cd ./$INFRA_DIR_BOILERPLATE && boilerplate --template-url . --output-folder . --non-interactive --var-file config_vars.yml
    #   env:
    #     INFRA_DIR_BOILERPLATE: scadev

    - name: 'Step 6 - Run Linting Checks'
      run: |
          pip install pre-commit
          git fetch origin
          git diff --color origin/main origin/{{ github.ref }}
          pre-commit run --show-diff-on-failure --color=always --from-ref origin/main --to-ref {{ github.ref }} --verbose
      continue-on-error: true