name: Boilerplate workflow
run-name: Generate boilerplate argocd-ska config

on:
  push:
    branches-ignore:
      - 'main'
      - 'master'

jobs:
  create_secrets:
    name: 'Job 0 - Create secrets'
    runs-on: ubuntu-latest
    steps:
      - name: 'Step 1'
        run: |
           echo openssl rand -base64 42
        
    

