name: 'test conditional'
on:
  workflow_dispatch:
    inputs:
      tfmode:
        description: 'Terraform mode'
        required: true
        default: 'plan'
        type: choice
        options:
        - plan
        - apply
        - destroy
      tfenv:
        description: 'Environment to run terrafom tfstate'
        required: true
        default: env1
      project_alias:
        description: 'Project Identifier'
        default: pilot
        required: true

permissions:
  contents: read

jobs:
  terraform:
    name: 'TestDynamicInput'
    runs-on: ubuntu-latest
    environment: gcp
    outputs:
      path: ${{ steps.version.outputs.propStr }}
      product: ${{ steps.get_product.outputs.propStr }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: get version
      id: version
      uses: notiz-dev/github-action-json-property@release
      with:
        path: '${{ github.workspace }}/folder/keyfile.json'
        prop_path: '${{ inputs.project_alias}}.environments.${{ inputs.tfenv }}.prefix'
    - name: get product
      if: ${{ inputs.tfmode == 'destroy' }}
      id: get_product
      uses: notiz-dev/github-action-json-property@release
      with:
        path: '${{ github.workspace }}/folder/keyfile.json'
        prop_path: '${{ inputs.project_alias}}.environments.${{ inputs.tfenv }}.product'
  verify_output:
    name: Verify
    runs-on: ubuntu-latest
    if: ${{ inputs.tfmode == 'destroy' }}
    needs: ['terraform']
    steps:
        - name: Echo product name
          shell: bash
          run: |
            echo ${{ needs.terraform.outputs.product }}




