name: 'test conditional'
on:
  workflow_dispatch:
    inputs:
      tfenv:
        description: 'Environment to run terrafom tfstate'
        required: true

permissions:
  contents: read

jobs:
  terraform:
    name: 'TestDynamicInput'
    runs-on: ubuntu-latest
    environment: gcp

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # - name: read-yaml-file
    #   uses: pietrobolcato/action-read-yaml@1.0.0
    #   id: read_action_js
    #   with:
    #     config: ${{ github.workspace }}/folder/keyfile.yaml

    # - name: Test Input
    #   run: |
    #     sudo apt install -y jq
    #     value=$(cat ${{ github.workspace }}/folder/keyfile.yaml | jq -r .${{ inputs.tfenv }} )
    #     echo $value
    - name: get version
      id: version
      uses: notiz-dev/github-action-json-property@release
      with:
        path: '${{ github.workspace }}/folder/keyfile.json'
        prop_path: '${{ inputs.tfenv }}'
    - name: Output value
      run: echo terraform init -backend=true -backend-config="bucket=ccon-gcp-${{ inputs.tfenv }}-tfstate" -backend-config="prefix=${{steps.version.outputs.propStr}}"