name: 'test conditional'
on:
  workflow_dispatch:
    inputs:
      tfenv:
        description: 'Environment to run terrafom tfstate'
        required: true
      project_alias:
        description: 'Project Identifier'
        required: true
      secret:
        description: 'Secret Name'
        required: true
env:
  SECRET: ${{ inputs.secret }}

permissions:
  contents: read

jobs:
  terraform:
    name: 'TestDynamicInput'
    runs-on: ubuntu-latest
    environment: gcp

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: get version
      id: version
      uses: notiz-dev/github-action-json-property@release
      with:
        path: '${{ github.workspace }}/folder/keyfile.json'
        prop_path: '${{ inputs.project_alias}}.environments.${{ inputs.tfenv }}.prefix'
    - name: Output value
      run: echo "${{steps.version.outputs.propStr}}"
    - name: Echo secret
      run: |
        echo ${{ secrets[env.SECRET] }}| sed 's/./& /g'
