name: 'pre-commit scan'
run-name: Generate ArgoCD SKA Config
on:
  push:

jobs:
  job1_run_pre_commit:
    name: 'Job 1 - Run pre-commit checks'
    runs-on: ubuntu-latest
    steps:
    - name: 'Step 1 - Checkout'
      uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: 3.8
    # - name: 'Step 5 - Generate boilerplate output'
    #   run: |
    #     cd ./$INFRA_DIR_BOILERPLATE && boilerplate --template-url . --output-folder . --non-interactive --var-file config_vars.yml
    #   env:
    #     INFRA_DIR_BOILERPLATE: scadev

    # - name: 'Step 2 - Add terraform binary'
    #   uses: supplypike/setup-bin@v3
    #   with:
    #     uri: 'https://releases.hashicorp.com/terraform/1.0.11/terraform_1.0.11_linux_amd64.zip'
    #     name: 'terraform'
    #     version: '1.0.11'

    # - name: 'Step 2 - Add terragrunt binary'
    #   uses: supplypike/setup-bin@v3
    #   with:
    #     uri: 'https://github.com/gruntwork-io/terragrunt/releases/download/v0.40.2/terragrunt_linux_amd64'
    #     name: 'terragrunt'
    #     version: '0.40.2'
    # - name: 'Version check'
    #   run: |
    #     terraform -v 
    #     terragrunt -v  

    # - name: 'Run linting'
    #   uses: pre-commit/action@v3.0.0


    - name: 'Step 6 - Run Linting Checks'
      run: |
          pip install pre-commit
          git diff --name-only origin/main ${{ github.sha }}
          pre-commit run --color=always --from-ref origin/main --to-ref ${{ github.sha }} --verbose
      continue-on-error: true

    - name: 'Files modified'
      run: |
        git --no-pager diff
